### ISSUE TITLE
Plugins tab list overflow on 3.8.0 release 283

### ISSUE THREAD

**Issue by jeffjl74** [EQAditu/AdvancedCombatTracker#108]
I have a lot of plugins. There used to be two rows of tabs. Now there is only one row. If I don't make the ACT window really wide, what should go on a second row of tabs is instead hiding "underneath" the one row that is displayed. Depending on which tab I click on, even the "Plugin Listing" tab is hidden.

**Comment by EQAditu** [comment]
Hmm, the overflow behavior was intended to be a scroll control such as this...
![image](https://github.com/user-attachments/assets/874c9b0c-1817-47f3-b83c-4b9e4670b47c)

Somehow I overlooked making sure that all of the tab controls were set up the same.  At the least, the next update will have this control.  I may look into supporting multiple lines, but it may look bad or act too funny to implement easily.

**Comment by jeffjl74** [comment]
Just noticed that the tab control on the Custom Triggers page has the same problem since I have a lot of "Results Tabs". A new blank line shows up between the sub-tabs and the "[Main][Options]" etc tabs, but no scroll arrows or tabs in the new line.

**Comment by EQAditu** [comment]
Thanks, I'll try to do a Solution search for the control type and verify each.

**Comment by jeffjl74** [comment]
Another wrinkle on those tab pages: if I use <Ctrl><Tab> keystroke to move between tab pages, the hidden line of tabs kinda shows up with just the focused tab in it if it was a hidden tab.

**Comment by EQAditu** [comment]
I assume you're talking about the multi-line issue and not the dotted rectangle keyboard focus cue?

---
Unfortunately when TabControl painting is overridden, WinForms decides to completely change how it allocates space for tabs and in many cases it does a poor job of knowing how much space is needed.  It makes edge cases like this or various DPI settings difficult because its estimation can end up very insufficient, forcing me to adapt margin/padding settings to each scenario.  My current plan is to go with the tab bar scrolling rather than multiple lines as the scrollbar actually works correctly.

**Comment by EQAditu** [comment]
New version should have a resolution.  Let me know if there's still an issue.
