### ISSUE TITLE
ACT blocks FFXIV parser 3.8.0.283 - Can't enable it

### ISSUE THREAD

**Issue by Scylune** [EQAditu/AdvancedCombatTracker#109]
Hello,

ACT disabled FFXIV_ACT_Plugin.dll. When I try to enable it again, it says it contains a virus.
I tried adding it to NOD32 exceptions, and even disable it.
Actually NOD32 is fully disabled and -ACT- refuses to enable the parser.

When I click on "Enable" :  "Bad Tmage Format"
Cannot load file or assembly '3445760 bytes loaded from ACT Version 3.8.0.283 ....' or one of its dependecies.
HRESULT : 0x800700E1

Btw, of course I've downloaded it again, disabled my antivirus, extracted it from the zip and put it back in the folder. 
ACT still refuses to enable it.

Thanks.

**Comment by EQAditu** [comment]
The problem is with ESET.
Similar: https://github.com/ravahn/FFXIV_ACT_Plugin/issues/323

There's nothing ACT can do about the file being blocked at the OS level.

This is not a simple false positive either, but the classification by ESET that is wrong.  ESET has correctly detected the Rust component used for memory procedures and decided to blacklist it.  The plugin author cannot do anything about this except to remove Deucalion completely.

**Comment by Scylune** [comment]
Hello,

Yes you're right. Thank you for your support.
