### ISSUE TITLE
Minimizing ACT to the system tray generates two invisible windows

### ISSUE THREAD

**Issue by MiguelArieiro** [EQAditu/AdvancedCombatTracker#110]
Enabling "Draw shading over the TreeView/DataGrid scrollbars" under "Color and Font Settings"-> "Main User interface" causes ACT to generate two invisible windows when it's minimized to the system tray. You may need to restart ACT in order to see the second window.

Open:
![image](https://github.com/user-attachments/assets/219e4290-d026-4da1-9202-0f7b4db7b115)
Minimized:
![image](https://github.com/user-attachments/assets/556b3cd1-c389-4fa5-8830-e3faf787c0e5)

These windows tend to disappear when maximizing ACT, but I've had one of them remain even after closing ACT. I've also had them not appearing at all a few times whilst attempting to pinpoint the bug. It's only been tested on three Windows 11 systems, which means it can be OS specific.

**Comment by EQAditu** [comment]
Thank you for your efforts, but I'm afraid that I've already fixed this bug for the next release.  I would have released it today, but I had another bug reported yesterday that I wanted to fix.

The gist of it is that the scrollbar shaders are themselves extra forms that attach themselves to the main window.  When the main window minimizes, Windows minimizes them as well *somehow* because they're parented.  The issue here is that minimizing to tray is not actually minimizing...  ACT stays as a normal restored window that is hidden.  For some reason Windows decides that the child windows with an invisible parent should appear in Alt-Tab.  The fix is simply to hide these child windows when the parent is hidden.

**Comment by MiguelArieiro** [comment]
That's good to hear!
Thanks for keeping ACT up and for the explanation. I'm a complete noob when it comes to Windows UI stuff :|

**Comment by EQAditu** [comment]
New version should have a resolution.  Let me know if there's still an issue.
