### ISSUE TITLE
Inconsistency in Line Separators When Copying Logs from Battle Log on Windows

### ISSUE THREAD

**Issue by MnFeN** [EQAditu/AdvancedCombatTracker#113]
### Environment
- Operating System: Windows

### Issue Description
When multiple lines from the battle log are selected and copied within the ACT environment, the line separators are denoted by "\n" instead of the Windows-standard "\r\n". This causes an issue when pasting these logs into other WinForm-based plugins of ACT; the pasted text does not recognize line breaks properly. Instead of starting a new line, the text continues with an invisible "\n" between the lines, which can lead to input errors and misinterpretation of the data.

### Expected Behavior
The copied text should use "\r\n" as a line separator to conform to Windows standards, ensuring proper line breaks when pasting text into other Windows-based applications or plugins.

### Steps to Reproduce
1. Open ACT and navigate to the battle log.
2. Select multiple lines of log data and copy them.
3. Paste the copied text into any other WinForm-based plugin within ACT.
4. Observe that the line breaks are not processed correctly, leading to continuous lines of text.

### Additional Context
This inconsistency can affect data parsing and display, making it difficult for users to interpret the logs accurately. Adjusting the line separator to the appropriate Windows format could resolve this input mishandling issue.

**Comment by EQAditu** [comment]
ACT has no feature called a battle log...  could not reproduce using the only thing I could think of...
![image](https://github.com/user-attachments/assets/f23ca999-bd21-47a1-9bbf-b9625e506d79)

**Comment by MnFeN** [comment]
> ACT has no feature called a battle log... could not reproduce using the only thing I could think of... ![image](https://private-user-images.githubusercontent.com/52854036/371385265-f23ca999-bd21-47a1-9bbf-b9625e506d79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjgwMjUsIm5iZiI6MTcyNzQyNzcyNSwicGF0aCI6Ii81Mjg1NDAzNi8zNzEzODUyNjUtZjIzY2E5OTktYmQyMS00N2ExLTliYmYtYjk2MjVlNTA2ZDc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA5MDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2Y2RiZDY0YmQwMTU5ZWQxZGZkYjJiYzFmYWEyNzBjMWM2MGYzMTk3YzZhMjMzNjljMDZiMzgzYTlkM2VjY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.gX3Ttjs0HRaCNbfGmoOaGuNH322Xp1LZy3gfRaCWz_s)

Thank you for the response. Here are the screenshots of my log and copied data (without `\r`):

<img src="https://github.com/user-attachments/assets/43c52bf8-6d86-40d7-bece-a02f1c826124" width="600">

<img src="https://github.com/user-attachments/assets/6df920ce-ff6f-4720-be5f-10b96b72370d" width="300">

The decompiled methods also did not contain `\r`:

![image](https://github.com/user-attachments/assets/ed0536b9-9ef3-469c-a566-0d457920fc53)

It could be better if the extra linebreak after the final line could be removed. Thanks!

**Comment by EQAditu** [comment]
The main problem with this request is that WinForms itself is not consistent.  When you type "1\<Enter\>2" in a RichTextBox, you create 3 characters; in a TextBox it creates 4.  
![image](https://github.com/user-attachments/assets/33aa0df6-2b70-48cd-8a40-d8e990649507)

Forcing `1\r\n2` will be displayed differently in a TextBox vs a RichTextBox. (4 characters)
![image](https://github.com/user-attachments/assets/02b60a2a-75fc-470c-aedf-18f7b7855503)

`1\n2` will be shown the same way in both.  (3 characters)
![image](https://github.com/user-attachments/assets/57665049-5baa-45dd-8fa1-b2c8595d1de3)
This makes `\n` the safest solution to use unless you are using text files on your filesystem.

`\r` is also not compatible with Linux WINE control text rendering... it will show a hollow box instead of it being invisible, so I avoid using it anywhere a WinForms control will be used such as message boxes or any control.

*I'm still considering how to handle this.*

**Comment by EQAditu** [comment]
I'm trying to use `Environment.NewLine` where possible to maintain compatibility with Linux.  I still don't know your usecase, but if you have direct control over it... RichTextBoxes are far more tolerant when compared to TextBoxes forced into multi-line mode.  

Some features in ACT are meant to be pasted directly into game chat which does not always handle `\r` well.  (I'm trying not to break things that have worked for over a decade)  Encounter Logs are always bad to paste into game chat... so I hope people are never doing that for any game.  Custom Trigger results, I cannot decide about since they are safer to paste because they lack the timestamp format to confuse ACT reading back the output.

**Comment by MnFeN** [comment]
> I'm trying to use `Environment.NewLine` where possible to maintain compatibility with Linux. I still don't know your usecase, but if you have direct control over it... RichTextBoxes are far more tolerant when compared to TextBoxes forced into multi-line mode.
> 
> Some features in ACT are meant to be pasted directly into game chat which does not always handle `\r` well. (I'm trying not to break things that have worked for over a decade) Encounter Logs are always bad to paste into game chat... so I hope people are never doing that for any game. Custom Trigger results, I cannot decide about since they are safer to paste because they lack the timestamp format to confuse ACT reading back the output.

Thank you, I previously did not know the differences between TextBox and RichTextBox. We paste the log lines into a TextBox within Triggernometry (an ACT plugin) to simulate test inputs and fire triggers. Based on your reply, it seems better to solve this issue on the plugin side.

**Comment by EQAditu** [comment]
The recent update may have results closer to what you are looking for.
