### ISSUE TITLE
ACT wont open for me. Says "InitACT 10... (Setting up log file, scannig for zone/name info)

### ISSUE THREAD

**Issue by wrackie** [EQAditu/AdvancedCombatTracker#12]

**Comment by EQAditu** [comment]
This usually happens when two FFXIV Plugins are run at the same time, causing a feedback loop, and the created network log is many GB large.  ACT has to scan through the huge log file for what it's looking for, which will be hard to find because the network log is filled with garbage instead of normal parsing.  You should rename or delete the problem log file before starting ACT again.

PS... this is not a troubleshooting area.  Use the forums or Discord if you need help.
