### ISSUE TITLE
Error on Download/Enable Plugin

### ISSUE THREAD

**Issue by victaxel** [EQAditu/AdvancedCombatTracker#14]
Hi, I clicked an update prompt (I don't remember if it was for the client or the parser plugin) and the update process crashed. Now this error is thrown after an uninstall and reinstall when I click Download/Enable Plugin.

![image](https://user-images.githubusercontent.com/49948470/73000969-f97f9980-3e01-11ea-8225-1bd007cc4ba7.png)

When I click the dialog, the following error pops up:
![image](https://user-images.githubusercontent.com/49948470/73001032-174cfe80-3e02-11ea-8b92-44e589c7970a.png)

**Comment by EQAditu** [comment]
There hasn't been an ACT update since December.  I haven't seen that specific error mentioned in the FFXIV Plugin Discord.  If you're actually uninstalling, I would allow the uninstaller to remove all folders when prompted.  Otherwise, you'll need to get support from places more specific to FFXIV.

PS.  This isn't really a troubleshooting forum.
