### ISSUE TITLE
Add Publisher & Version info to installer

### ISSUE THREAD

**Issue by andrewbabbittdev** [EQAditu/AdvancedCombatTracker#33]
I have added ACT over to the winget community repository. There has been a request on their side for you to add publisher and version info to your installer as they are missing from the control panel uninstall list.

For more info check microsoft/winget-pkgs#19346

**Comment by EQAditu** [comment]
Sorry, I've been very busy and didn't have a chance to look at this until now.

I currently write the following strings to the registry to allow uninstall functionality...
```
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Advanced Combat Tracker" "DisplayName" "Advanced Combat Tracker (remove only)"
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Advanced Combat Tracker" "UninstallString" '"$INSTDIR\Uninstall-ACT.exe"'
```
I'll have to do some research on what strings are required for those other things that you want.  The main issue with "version" is that it won't change when the program updates normally.  The installer will set these strings, but it is not required to "install" ACT, so these uninstall strings may not even exist on some computers to update.  I might be able to get the updater to check for these registry strings and update them properly... but I'm not sure.

**Comment by EQAditu** [comment]
I can go as far as this:
```
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Advanced Combat Tracker" "DisplayName" "Advanced Combat Tracker (remove only)"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Advanced Combat Tracker" "UninstallString" '"$INSTDIR\Uninstall-ACT.exe"'
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Advanced Combat Tracker" "DisplayIcon" '"$INSTDIR\Uninstall-ACT.exe",0'
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Advanced Combat Tracker" "URLInfoAbout" "https://advancedcombattracker.com"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Advanced Combat Tracker" "Publisher" "EQAditu"
	WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Advanced Combat Tracker" "DisplayVersion" $R0
```
But Windows 10 strips down the display to just:
![image](https://user-images.githubusercontent.com/52854036/125094191-0b5e0680-e0a1-11eb-91b8-79c0a9abfa72.png)

**Comment by andrewbabbittdev** [comment]
No problem, I totally get being busy.

> The main issue with "version" is that it won't change when the program updates normally. The installer will set these strings, but it is not required to "install" ACT, so these uninstall strings may not even exist on some computers to update. I might be able to get the updater to check for these registry strings and update them properly... but I'm not sure.

@OfficialEsco Just FYI ACT runs its updates through a dialog when starting the program, downloads the latest bits and updates without another installer. Any guidance or considerations for Winget?

Only things asked for Winget was the addition of the `Publisher` and `DisplayVersion` fields, `DisplayIcon` is however nice to have. `UrlInfoAbout` isnt shown anywhere except in the old control panel. Just FYI starting in Windows 11 this is how it will look:

![apps](https://user-images.githubusercontent.com/2308261/125134380-8a186b00-e0c4-11eb-8a2d-76b54edd34ba.png)

**Comment by EQAditu** [comment]
Updates technically have another NSIS installer, but it's not the same as the original installer.  ACT doesn't have to run as admin, so it can't always access Program Files, so the update is another NSIS package that does run as admin... but it's a much more simple one that typically runs silently and doesn't create an uninstaller at all.  I can make it update the uninstall DisplayVersion, though.  (if it exists)

**Comment by OfficialEsco** [comment]
Won't it prompt for Administrator if its required tho? Not sure how installers work, but you could also make it a user install which installs in `%LOCALAPPDATA%\Programs`, then it won't prompt for Administrator.

**Comment by EQAditu** [comment]
The NSIS installers are flagged to require elevation, so when you run the setup manually or ACT runs the downloaded update, there will be an elevation request.  I suppose this will also happen when ACT is extracted from a ZIP and that copy tries to update.  It's somewhat a moot point because right now, 80%+ of the userbase plays a specific MMO that requires ACT to run as admin just to get data properly.

**Comment by andrewbabbittdev** [comment]
> Updates technically have another NSIS installer, but it's not the same as the original installer.

What is the reasoning behind doing this, why not use the same original installer just with a silent flag? If it were done like this you could just have your installer set the registry keys and because you are using the same installer for updates any time someone does an update either by downloading a new installer or running it when ACT prompts them to update then those keys will be updated as well.

**Comment by EQAditu** [comment]
Because the update package was much smaller.  I was paying for tiered bandwidth once upon a time and ACT has no intentional income.  Also, you forgot the part where ACT does not require installation and I have always said you can just unzip it and run it.  Force the updater to use the original installer logic, and then you're adding stuff to the registry.  ACT does not explicitly use the registry and if you run ACT in portable mode, just deleting the folder wipes everything as designed.

Edit:  Maybe I should add the most relevant reason...  before now, why would I update the uninstall string?  Most people don't look at the uninstall settings to find out about a program.  I'm only adding it now because you requested it... not because I think it is otherwise useful.

**Comment by EQAditu** [comment]
Released

**Comment by OfficialEsco** [comment]
Uhm, the DisplayVersion string is blank
![VirtualBoxVM_kQSZedQDOm](https://user-images.githubusercontent.com/15158490/147279269-406d9dee-4b2a-481e-97de-6604250d5852.png)

**Comment by EQAditu** [comment]
This is what I get with a fresh install:
![image](https://user-images.githubusercontent.com/52854036/147280326-8b310b69-ca33-43f2-8a99-4a54848c0086.png)
![image](https://user-images.githubusercontent.com/52854036/147280334-86dfaca3-723a-4c07-9400-8aacdd11e613.png)

**Comment by OfficialEsco** [comment]
Tested as User and Administrator and checked the regstring you pointed to, however still blank
![VirtualBoxVM_yiKOaWWJwM](https://user-images.githubusercontent.com/15158490/147280847-e515e558-412a-4c87-82f6-b2f112b67e01.png)

**Comment by EQAditu** [comment]
So, my Windows 10 machine acts differently to my Windows 11 machine.
![2021-12-23 13_50_19-Window](https://user-images.githubusercontent.com/52854036/147281845-3470d7e1-c019-49f4-b730-c97652d891f1.png)
![image](https://user-images.githubusercontent.com/52854036/147281861-bef23566-6b6b-41ee-b38d-a9fa6d429d30.png)


I don't know how I feel about the same installer doing two different things or how to go about fixing it.

**Comment by EQAditu** [comment]
I see what is happening, I think.  It wasn't obvious to me when I was making this work... but apparently the version string is created at runtime and not when the installer was created.  The installer is looking at the source files when figuring out the version number.  This works fine on the machine that created the installer... but not for anyone else because the path doesn't exist.  The path doesn't exist, so the DisplayVersion is blank.

**Comment by EQAditu** [comment]
Since the program/updater wasn't changing, I just re-uploaded the installer with the fix, but I think winget's system doesn't appreciate it.
![2021-12-23 14_24_31-Window](https://user-images.githubusercontent.com/52854036/147284092-b700692c-e062-4918-ac51-64b7064c6f37.png)
I've never tried this before with winget, but I assume this is not normal.

**Comment by OfficialEsco** [comment]
One moment, it got approved before your fix, didn't know how and when you would fix it so i let it pass, thank you for the quick fix :)
