### ISSUE TITLE
Selection of a certain process is partial

### ISSUE THREAD

**Issue by Murkchan** [EQAditu/AdvancedCombatTracker#36]
Immediately I apologize for the Google translation

After selecting a certain process, only the combat log track is switched. However, the data of the active character remains from the first automatically selected process. Synchronization does not occur with the selected process.

Perhaps it would be easier if ACT automaticaly selected the game process of the same user from which ACT was launched.

**Comment by EQAditu** [comment]
This sort of thing is specific to FFXIV, which I can't change anything about.
https://github.com/ravahn/FFXIV_ACT_Plugin

Additionally, Cactbot doesn't handle multiple game processes well: https://github.com/quisquous/cactbot/issues/3353

**Comment by gamer4eg** [comment]
This is very sad. There are people using a PC at the same time (several users).
[(Here)](https://www.ibik.ru/) is an example of a program that allows you to divide a PC into several simultaneous workstations. (This is not a virtual machine, there is almost no performance loss)
If it cannot be fixed, can you advise how to hide the unnecessary process of the game client from the ACT?

**Comment by EQAditu** [comment]
I'm not saying it cannot be fixed.  I am saying that I am not the author of the FFXIV Plugin and this problem is specific to FFXIV.  I can only fix things that are directly part of ACT... whereas the FFXIV Plugin is written by someone else.

ACT, the FFXIV Plugin, OverlayPlugin and Cactbot are all written by at least 4 different people.  Depending on what the problem is, one of the others would have to fix it instead of me.

**Comment by gamer4eg** [comment]
Understood. It is necessary to create an issue in the repository of the author of the cactbot.

**Comment by EQAditu** [comment]
If the problem is specific to Cactbot... I already linked the Cactbot issue above, so you don't need to create another one.  The author of Cactbot created the issue, so they definitely know about it.  It is just not fixed yet.
