### ISSUE TITLE
no overlay

### ISSUE THREAD

**Issue by dcostello199** [EQAditu/AdvancedCombatTracker#48]
okay so since over a week im trying to get advanced combat tracker for ff14. now im doing everything STEP BY STEP. i even uninstalled and re installed several times and no matter what i do when i go to "Get Plug-ins" ffxiv overlay plug in WILL NOT pop up.. no matter what i do. i looked at guides. even ur guide on how to install and did STEP  BY STEP and ffxiv overlay plug in isnt popping up on get plug ins... pls pls help all i want is to use this dps meter addon and since weeks i can not get plug in to get in there. so i cant go foward... pls get back to me and help me get ffxiv plug in. thank you so much. pls help ASAP

**Comment by EQAditu** [comment]
I have never made a guide on the subject, so I'm not certain what you're referring to.  

Parsing plugins are not available on the Get Plugins wizard because you should *never* install more than one at a time.    If you have no parsing plugin, the Startup Wizard should prompt you to get one which it will download for you.  If you want to manually trigger the Startup Wizard, you can find it at the top of the Options tab.  

Otherwise, there is no such thing as an "ffxiv overlay plugin".  There is OverlayPlugin but that is not specific to FFXIV.  The FFXIV parsing plugin no longer has any overlays built-in.  Any such functionality can be handled by OverlayPlugin and an appropriate preset.

**Comment by seanren78** [comment]
I am still unable to get the overlay on my top of my game.  I can have it off screen on a monitor and functions correctly, but does but cannot place in-game.

**Comment by dcostello199** [comment]
If you look at the steps on the step by step on how to get this and get it working for ff14 on 1 of the steps in the pictures on the plug ins there is a “ffxiv overlay plugin” when getting plugins and I don’t have it as an option to plug in. I have done every step shown on website guide. And still it is not there. And due to not having the ffxiv overlay plugin as an option it will not let me use or run this on ff14. Also seen 20-30 guides online and all of the persons showing has the ffxiv overlay plugin. And idk how to get it there. I tried everything

**Comment by EQAditu** [comment]
I still have no idea what guide you're talking about.  **<ins>I have never written a guide.</ins>**

Old guides are old and the internet will keep them forever.  It doesn't mean they are right forever and you should be blind to change.  And no, there was *never* something that said "ffxiv overlay plugin".  The "FFXIV Overlay Settings" tab was part of the main FFXIV Plugin and has since been removed as alluded to.

As I already said:
> The FFXIV parsing plugin no longer has any overlays built-in. Any such functionality can be handled by OverlayPlugin and an appropriate preset.

*PS. If you quote something and the quote is not correct, I won't believe you.  Only use quotation marks when applicable.  Do not use quotation marks when you're guessing something as that is not a quote.  Those are your own words.*
