### ISSUE TITLE
No Overlay In-game

### ISSUE THREAD

**Issue by seanren78** [EQAditu/AdvancedCombatTracker#49]
I cannot get the overlay for in-game.  I can have the meter off-screen on another monitor.  I have tried every trouble shoot online and am still sadly having issues.

**Comment by EQAditu** [comment]
The main ACT project has no overlays unless you mean the window that appears when you click **Show Mini**.  Since I doubt you are, I suggest you focus your efforts on the appropriate project.  You don't say what type of overlay you're talking about, so it could be from several different plugins which will have completely different answers to this subject.

Look at this and choose appropriately...  https://github.com/EQAditu/AdvancedCombatTracker/issues/16
I strongly recommend you look for support in Discord and not GitHub because that's not what these issue trackers are for.
