### ISSUE TITLE
Request for Plugin ID

### ISSUE THREAD

**Issue by FreedomFaighter** [EQAditu/AdvancedCombatTracker#63]
EverQuest Damage Per Second Plugin
Plugin for ACT EverQuest Damage Per Second Parsing
EverQuest
GitHub
https://api.github.com/repos/FreedomFaighter/ACT_EQ_DPS_Plugin/releases/latest
https://github.com/FreedomFaighter/ACT_EQ_DPS_Plugin/issues
Egot

**Comment by EQAditu** [comment]
The release you made has no files to download.  You should compile the plugin and attach the file to your release.  It could be as a .dll or .zip...  ACT's download wizard will figure out either one, but it does change your update logic, when you write it.

It does not need to be titled "latest".  The GitHub API will know which is the latest already, as long as it is not marked pre-release or draft.

The "tag" you give the release should be the version number of your compiled file.  ACT and the website will use this value to determine the version for display purposes and in the API to see the version available on the web for knowing *when* to update.  It looks like you're using automatic versioning in your assembly, so you will have to compile to see the resulting number instead of `0.0.*`.

Take a look at ACT's last release: https://github.com/EQAditu/AdvancedCombatTracker/releases/tag/3.6.2.279
The tag is ACT's version number and the Assets section has compiled files to download.  (Assets are in alphabetical order if you have more than one)

**Comment by EQAditu** [comment]
Given ID #92.
You can use https://advancedcombattracker.com/versioncheck/pluginversion/92 to verify version number changes.

**Comment by FreedomFaighter** [comment]
Change to [https://github.com/FreedomFaighter/AdvancedCombatTrackerEverQuest](https://github.com/FreedomFaighter/AdvancedCombatTrackerEverQuest) for Update works
