### ISSUE TITLE
Tried Everything

### ISSUE THREAD

**Issue by matthew88166** [EQAditu/AdvancedCombatTracker#64]
I have tried everything to try and get the Act Combat Tracker to work again, i uninstalled it  from my machine. i checked everything you name it but one thing i did notice is when you got ready to pick a overlay screen or type you wanted id pick it and then it would pop up and id see my name and some other players on the little screen well once i click ok those names go away and i never see them come back again. i dont know what is going on but it seems every time FF14 is updated the tracker is always having issues of some sort. can you look into this for me please? thank you

**Comment by EQAditu** [comment]
This is not meant to be a support forum but an issue tracker for ACT.  See pinned issue #16.

Your difficulty appears to be with OverlayPlugin (https://github.com/OverlayPlugin/OverlayPlugin) and/or the FFXIV parsing plugin (https://github.com/ravahn/FFXIV_ACT_Plugin).

Every game patch with FFXIV will *require* an update to the parsing plugin before anything will work again.  It has been this way for a very long time and should be expected for *every* game patch.  OverlayPlugin will background-download some helper files after game patches instead of a full update.  It vaguely sounds like your settings for hiding overlays when the game is not focused aren't working for you.  They either work or don't, I can't help you with that.  Overlays will never work if the parsing plugin and main ACT window does not.
